In [1]:
import numpy as np


In [12]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [85]:
training_inputs = np.array([[0,0,1],
                            [1,1,1],
                            [1,0,1],
                            [0,1,1]])

In [86]:
training_outputs = np.array([[0,1,1,0]]).T
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [87]:
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3, 1)) - 1
synaptic_weights

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [39]:
outputs = sigmoid(np.dot(training_inputs, synaptic_weights))
outputs

array([[0.2689864 ],
       [0.3262757 ],
       [0.23762817],
       [0.36375058]])

In [40]:
error = training_outputs - outputs
error

array([[-0.2689864 ],
       [ 0.6737243 ],
       [ 0.76237183],
       [-0.36375058]])

In [41]:
adjustments = error * sigmoid_derivative(outputs)
adjustments

array([[-0.05289153],
       [ 0.14809799],
       [ 0.13811206],
       [-0.08418501]])

In [14]:
synaptic_weights += np.dot(training_inputs.T, adjustments)
synaptic_weights

array([[ 0.12025406],
       [ 0.50456196],
       [-0.85063774]])

In [15]:
outputs = sigmoid(np.dot(training_inputs, synaptic_weights))
outputs

array([[0.29929909],
       [0.44378327],
       [0.32511054],
       [0.41433436]])

In [42]:
def train(training_inputs, training_outputs, synaptic_weights, iterations):
    for _ in range(iterations):
        outputs = sigmoid(np.dot(training_inputs, synaptic_weights))
        error = training_outputs - outputs
        adjustments = error * sigmoid_derivative(outputs)
        synaptic_weights += np.dot(training_inputs.T, adjustments)
    return outputs

In [91]:
synaptic_weights

array([[12.70627854],
       [-0.20392447],
       [-6.14946022]])

In [90]:
outputs = train(training_inputs, training_outputs, synaptic_weights, 100000)
outputs

array([[0.00213009],
       [0.99826132],
       [0.99858161],
       [0.00173782]])